services:
  kafka:
    image: apache/kafka:3.9.0
    container_name: metric-kafka
    ports:
      - "9092:9092"   # Docker 내부 통신용
      - "9094:9094"   # 로컬 IDE 앱 접속용
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - metric-net

  postgres:
    image: postgres:16
    container_name: metric-postgres
    ports:
      - "6432:5432"
    environment:
      POSTGRES_DB: metricdb
      POSTGRES_USER: metric
      POSTGRES_PASSWORD: metric1234
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - metric-net

  grafana:
    image: grafana/grafana:10.4.0
    container_name: metric-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_SECURITY_ALLOW_EMBEDDING=true
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    depends_on:
      - postgres
    networks:
      - metric-net

networks:
  metric-net:
    driver: bridge

volumes:
  kafka-data:
  postgres-data:
  grafana-data:
