spring:
  application:
    name: metric-generator
  jackson:
    serialization:
      write-dates-as-timestamps: false
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

metric:
  kafka:
    topic: server-api-logs

logging:
  level:
    com.juneyoung: DEBUG
